* Project goal

Build an external mapping tool that can process credit card transaction CSV file downloads and
ensure that there is way to assign each item in the file to an expense category in gnucash. The
mapping tool creates a mapping file that has regular expressions associated with "account path" strings
such that processing the cc file can produce a modified version that will import properly into
gnucash.

** Artifacts:

*** matcher_map.csv

Permanent result of operations, regular expression and account mapping.
Example:

cc_desc_re,re_no_case,account_path
"^amazon\.com",True,Expenses|online_shop|Amazon

The re_no_case column tells the processor code to apply no case flag on match attempts
The "account_path" column is meant to be split on the pipe character, such that each
element of the split is a child of the previous element.


*** account_defs.csv
Temporary file generated from gnucash that contains the list of expense type accounts
defined in gnucash. One (optional) element of the process is to edit this file to add
new accounts that should be created in the gnucash file, which can be done by one of the
tools.


*** no_match_results.csv
Temporary file containing each input description that did not get matched by the matcher_map.csv
data. The matcher_map.csv file needs updating to have a matcher for this item and possibly the
account_defs.csv does too.


*** gnucash backup file

Created before any operation that modifies the gnucash file.

*** Modified Input files


1. Parse input csv files, check against matcher_map.csv, report any lines that have no matcher
   in "missing_matchers.csv". check_phases.py::check_10
2. Edit any missing - edit_phases:edit_10_ods
3. Export accounts from gnucash Check matchers against accounts - check_20.py
   1. If accounts exist but have no matcher, manually update matcher_map.csv  - edit_20.py
   2. If any input matchers name accounts that are missing from gnucash accounts
      1. edit account_defs.py - edit_30.py
      2. Backup gnucash file, then sync accounts csv file with gnucash - update_30.py
4. Repeat above steps until nothing unmatched or missing.
5. Create modified input csv files that have gnucash account specified in gnucash_account column
6. Import cvs files in gnucash
   
   

** Edit idea

1. When looking at missing matches, it should be possible to test the regexp that the user supplies
   against all the file listed. First find the exact matches in each file, then run regex and ensure
   it finds the same lines.
